<?php
/**
 * @file
 * wwm_media_feature.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function wwm_media_feature_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_file_audio_caption'
  $field_bases['field_file_audio_caption'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_file_audio_caption',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_file_audio_credit'
  $field_bases['field_file_audio_credit'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_file_audio_credit',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_long',
  );

  // Exported field_base: 'field_file_audio_license'
  $field_bases['field_file_audio_license'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_file_audio_license',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'None (all rights reserved)' => 'None (all rights reserved)',
        '-- Creative Commons --' => '-- Creative Commons --',
        'Attribution, Non-Commercial, Share Alike' => 'Attribution, Non-Commercial, Share Alike',
        'Attribution, Non-Commercial' => 'Attribution, Non-Commercial',
        'Attribution, Non-Commercial, No Derivative Works' => 'Attribution, Non-Commercial, No Derivative Works',
        'Attribution' => 'Attribution',
        'Attribution, Share Alike' => 'Attribution, Share Alike',
        'Attribution, No Derivative Works' => 'Attribution, No Derivative Works',
      ),
      'allowed_values_function' => '',
      'allowed_values_php' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_file_document_caption'
  $field_bases['field_file_document_caption'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_file_document_caption',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_file_document_credit'
  $field_bases['field_file_document_credit'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_file_document_credit',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_long',
  );

  // Exported field_base: 'field_file_document_license'
  $field_bases['field_file_document_license'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_file_document_license',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'None (all rights reserved)' => 'None (all rights reserved)',
        '-- Creative Commons --' => '-- Creative Commons --',
        'Attribution, Non-Commercial, Share Alike' => 'Attribution, Non-Commercial, Share Alike',
        'Attribution, Non-Commercial' => 'Attribution, Non-Commercial',
        'Attribution, Non-Commercial, No Derivative Works' => 'Attribution, Non-Commercial, No Derivative Works',
        'Attribution' => 'Attribution',
        'Attribution, Share Alike' => 'Attribution, Share Alike',
        'Attribution, No Derivative Works' => 'Attribution, No Derivative Works',
      ),
      'allowed_values_function' => '',
      'allowed_values_php' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_file_image_caption'
  $field_bases['field_file_image_caption'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_file_image_caption',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_file_image_credit'
  $field_bases['field_file_image_credit'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_file_image_credit',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_long',
  );

  // Exported field_base: 'field_file_license'
  $field_bases['field_file_license'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_file_license',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'None (all rights reserved)' => 'None (all rights reserved)',
        '-- Creative Commons --' => '-- Creative Commons --',
        'Attribution, Non-Commercial, Share Alike' => 'Attribution, Non-Commercial, Share Alike',
        'Attribution, Non-Commercial' => 'Attribution, Non-Commercial',
        'Attribution, Non-Commercial, No Derivative Works' => 'Attribution, Non-Commercial, No Derivative Works',
        'Attribution' => 'Attribution',
        'Attribution, Share Alike' => 'Attribution, Share Alike',
        'Attribution, No Derivative Works' => 'Attribution, No Derivative Works',
      ),
      'allowed_values_function' => '',
      'allowed_values_php' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_file_video_caption'
  $field_bases['field_file_video_caption'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_file_video_caption',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_file_video_credit'
  $field_bases['field_file_video_credit'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_file_video_credit',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_long',
  );

  // Exported field_base: 'field_file_video_license'
  $field_bases['field_file_video_license'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_file_video_license',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'None (all rights reserved)' => 'None (all rights reserved)',
        '-- Creative Commons --' => '-- Creative Commons --',
        'Attribution, Non-Commercial, Share Alike' => 'Attribution, Non-Commercial, Share Alike',
        'Attribution, Non-Commercial' => 'Attribution, Non-Commercial',
        'Attribution, Non-Commercial, No Derivative Works' => 'Attribution, Non-Commercial, No Derivative Works',
        'Attribution' => 'Attribution',
        'Attribution, Share Alike' => 'Attribution, Share Alike',
        'Attribution, No Derivative Works' => 'Attribution, No Derivative Works',
      ),
      'allowed_values_function' => '',
      'allowed_values_php' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  return $field_bases;
}
